name: Submodulo_6AM_PRG

executables:
  slidy: main
  fvm:
environment:
  sdk: '>=1.19.0 <3.0.0'
  flutter: ^0.1.2
  
dependencies:
  path: ^1.3.0
  collection: ^1.1.0
  string_scanner: ^0.1.2
  
dependencies:
  efts: ^2.0.4
  transmogrify: ^0.4.0
  
dev_dependencies:
  test: '>=0.5.0 <0.12.0'
  
dev_dependencies:
  test: '>=1.15.0 <2.0.0'
  
  transmogrify: ^1.2.0
dependency_overrides:
  transmogrify: '3.2.1'
