name: hide_hello_dear
description: >-
  Have you been turned into a newt?  Would you like to be?
  This package can help. It has all of the
  newt-transmogrification functionality you have been looking
  for.
version: 2.5.3
homepage: https://github.com/jonnyGh34255/Submodulo-Aplicaciones-iOS-6AM.git
documentation: https://github.com/github/docs

environment:
  sdk: '>=2.10.0 <3.0.0'
  
dependencies:
  efts: ^2.0.4
  transmogrify: ^0.4.0
    
executables: 
name: Flutter analyze
script: flutter analyze
name: Flutter unit tests
  script: flutter test
name: Build debug iOS app
  script: flutter build ios --debug --no-codesign

dev_dependencies:
  test: '>=1.15.0 <2.0.0'
  
publish_to: none

environment:
  sdk: '>=1.19.0 <3.0.0'
  flutter: ^0.1.2
  
