name: MyApp

description: >-
  Have you been turned into a newt?  Would you like to be?
  This package can help. It has all of the
  newt-transmogrification functionality you have been looking
  for.
version: 2.5.3
homepage: https://github.com/jonnyGh34255/Submodulo-Aplicaciones-iOS-6AM.git
documentation: https://github.com/github/docs

environment:
  sdk: '>=2.5.3 <3.0.0'
  
dependencies:
  efts: ^2.5.3
  transmogrify: ^0.4.0
  
  environment: 
   flutter_driver:
      


  
dev_dependencies:
  test: '>=2.5.3 <3.0.0'
  

